import{S,a as q,i as n}from"./assets/vendor-DWXSRYDZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();let f;function m(o){const t=o.map(({downloads:l,likes:c,comments:e,views:r,tags:a,webformatURL:b,largeImageURL:w})=>`
          <li class="gallery-item">
          <a class="gallery-link" href="${w}">
          <img class="gallery-image" src="${b}" alt="${a}">
          <ul class="info-wrapper">
          <li class="info-item"><span>likes</span>${c}</li>
          <li class="info-item"><span>Dounloads</span>${l}</li>
          <li class="info-item"><span>Comments</span>${e}</li>
          <li class="info-item"><span>Views</span>${r}</li>
          </ul>
          </a> 
          </li>  
    `).join("");s.gallery.insertAdjacentHTML("afterbegin",t),f?f.refresh():f=new S(".gallery a",{})}function v(){s.gallery.innerHTML=""}function p(){s.loader.classList.add("is-open")}function y(){s.loader.classList.remove("is-open")}function g(){s.more.classList.remove("hidden")}function u(){s.more.classList.add("hidden")}async function h(o,t){return(await q.get("https://pixabay.com/api/",{params:{key:"51327583-eda9110ddf8c3e7e62438a086",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:3,page:t}})).data}const s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),btn:document.querySelector(".search-button"),input:document.querySelector('input[name="search-text"]'),more:document.querySelector(".load-more")};s.form.addEventListener("submit",$);s.more.addEventListener("click",M);const L=15;let i,d="";async function $(o){if(o.preventDefault(),i=1,d=s.input.value.trim(),!d){n.error({title:"(",message:"Field search can t be empty"});return}v(),u(),p();try{const t=await h(d,i);if(t.hits.length===0){n.error({title:"(",message:"sorry,try again",position:"topRight"});return}else m(t.hits),console.log(t.hits),t.totalHits>i*L&&g()}catch(t){n.error({title:"(",message:"sorry"}),console.log(t)}finally{y(),s.form.reset()}}async function M(){i+=1,u(),p();try{const o=await h(d,i);o.totalHits<=i*L?(u(),n.info({title:"*",message:"This is all images ",position:"topRight"})):m(o.hits)}catch(o){n.error({title:"(",message:"sorry"}),console.log(o),u()}finally{y()}}
//# sourceMappingURL=index.js.map
