import{S,a as v,i}from"./assets/vendor-DWXSRYDZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function u(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=u(e);fetch(e.href,r)}})();let m;function p(o){const t=o.map(({downloads:u,likes:d,comments:e,views:r,tags:a,webformatURL:w,largeImageURL:b})=>`
          <li class="gallery-item">
          <a class="gallery-link" href="${b}">
          <img class="gallery-image" src="${w}" alt="${a}">
          <ul class="info-wrapper">
          <li class="info-item"><span>likes</span>${d}</li>
          <li class="info-item"><span>Dounloads</span>${u}</li>
          <li class="info-item"><span>Comments</span>${e}</li>
          <li class="info-item"><span>Views</span>${r}</li>
          </ul>
          </a> 
          </li>  
    `).join("");s.gallery.insertAdjacentHTML("beforeend",t),m?m.refresh():m=new S(".gallery a",{})}function $(){s.gallery.innerHTML=""}function f(){s.loader.classList.add("is-open")}function g(){s.loader.classList.remove("is-open")}function h(){s.more.classList.remove("hidden")}function c(){s.more.classList.add("hidden")}async function y(o,t){return(await v.get("https://pixabay.com/api/",{params:{key:"51327583-eda9110ddf8c3e7e62438a086",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),btn:document.querySelector(".search-button"),input:document.querySelector('input[name="search-text"]'),more:document.querySelector(".load-more")};s.form.addEventListener("submit",q);s.more.addEventListener("click",P);const L=15;let n,l="";async function q(o){if(o.preventDefault(),n=1,l=s.input.value.trim(),!l){i.error({title:"(",message:"You must enter something to search."});return}$(),c(),f();try{const t=await y(l,n);if(t.hits.length===0){i.error({title:"(",message:`Sorry, no images found matching your search ${l}. Please try again!`,position:"topRight"});return}else p(t.hits),t.totalHits>n*L?h():(c(),i.info({title:"*",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){i.error({title:"(",message:`Something went wrong! Please try your search again.${t}`}),console.log(t)}finally{g(),s.form.reset()}}async function P(){n+=1,c(),f();try{const o=await y(l,n);if(o.totalHits<=n*L)c(),i.info({title:"*",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});else{p(o.hits),f(),h();const{height:t}=s.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch(o){i.error({title:"(",message:`Something went wrong! Please try your search again.${o}`}),console.log(o),c()}finally{g()}}
//# sourceMappingURL=index.js.map
