import{S as q,a as P,i as d}from"./assets/vendor-DWXSRYDZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&u(n)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();let f;function m(r){const t=r.map(({downloads:c,likes:u,comments:e,views:o,tags:n,webformatURL:S,largeImageURL:v})=>`
          <li class="gallery-item">
          <a class="gallery-link" href="${v}">
          <img class="gallery-image" src="${S}" alt="${n}">
          <ul class="info-wrapper">
          <li class="info-item"><span>likes</span>${u}</li>
          <li class="info-item"><span>Downloads</span>${c}</li>
          <li class="info-item"><span>Comments</span>${e}</li>
          <li class="info-item"><span>Views</span>${o}</li>
          </ul>
          </a> 
          </li>  
    `).join("");s.gallery.insertAdjacentHTML("beforeend",t),f?f.refresh():f=new q(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function $(){s.gallery.innerHTML=""}function p(){s.loader.classList.add("is-open")}function g(){s.loader.classList.remove("is-open")}function y(){s.more.classList.remove("hidden")}function l(){s.more.classList.add("hidden")}async function h(r,t){return(await P.get("https://pixabay.com/api/",{params:{key:"51327583-eda9110ddf8c3e7e62438a086",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),btn:document.querySelector(".search-button"),input:document.querySelector('input[name="search-text"]'),more:document.querySelector(".load-more")};s.form.addEventListener("submit",M);s.more.addEventListener("click",D);const L=15;let i,a="";async function M(r){if(r.preventDefault(),i=1,a=s.input.value.trim(),!a){d.info({title:"(",message:"You must enter something to search.",position:"topRight"});return}$(),l(),p();try{const t=await h(a,i);if(t.hits.length===0){d.error({title:"(",message:`Sorry, no images found matching your search ${a}. Please try again!`,position:"topRight"});return}else m(t.hits),t.totalHits>i*L?y():(l(),w())}catch(t){b(),console.log(t)}finally{g(),s.form.reset()}}async function D(){i+=1,l(),p();try{const r=await h(a,i);m(r.hits);const{height:t}=s.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),r.totalHits<=i*L?(l(),w()):y()}catch(r){b(),console.log(r),l()}finally{g()}}function w(){d.info({title:"*",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function b(){d.error({title:"(",message:`Something went wrong! Please try your search again.${error}`})}
//# sourceMappingURL=index.js.map
